name: language-elm
version: '0.1.1.0'
synopsis: Generate elm code
description: Generate elm code from an ast
category: Web
author: Elias Lawson-Fox
maintainer: eliaslfox@gmail.com
copyright: 2017 Elias Lawson-Fox
license: BSD3
github: eliaslfox/language-elm
extra-source-files:
- README.md
dependencies:
- pretty
- mtl
- protolude
- base >= 4.11 && <= 4.12
build-tools:
- doctest
library:
  source-dirs: src
  exposed-modules:
  - Elm
  - Elm.Decleration
  - Elm.Expression 
  - Elm.Import
  - Elm.Program
  - Elm.Type
  - Elm.Classes
  - Elm.GenError
  dependencies:
  - MissingH
tests:
  language-elm-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language-elm
    - hspec
